=== Kampina/wi_520/dist/game/data/events/events.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (event)*>
<!ELEMENT event (parameter|on_start|on_stop|on_init|on_time|objects)*>
<!ATTLIST event
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	impl CDATA #REQUIRED>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT on_start  (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward)*>
<!ELEMENT on_stop   (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward)*>
<!ELEMENT on_init   (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward)*>
<!ELEMENT on        (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward)*>
<!ELEMENT if        (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward)*>
<!ELEMENT ifnot     (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward)*>
<!ELEMENT else      (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward)*>
<!ATTLIST if
	name CDATA #REQUIRED>
<!ATTLIST ifnot
	name CDATA #REQUIRED>
<!ELEMENT on_time (on)*>
<!ATTLIST on
	time CDATA #REQUIRED>
<!ELEMENT start (#PCDATA)>
<!ATTLIST start
	name CDATA #REQUIRED>
<!ELEMENT stop (#PCDATA)>
<!ATTLIST stop
	name CDATA #REQUIRED>
<!ELEMENT spawn (#PCDATA)>
<!ATTLIST spawn
	name CDATA #REQUIRED>
<!ELEMENT open (#PCDATA)>
<!ATTLIST open
	name CDATA #REQUIRED>
<!ELEMENT close (#PCDATA)>
<!ATTLIST close
	name CDATA #REQUIRED>
<!ELEMENT active (#PCDATA)>
<!ATTLIST active
	name CDATA #REQUIRED>
<!ELEMENT deactive (#PCDATA)>
<!ATTLIST deactive
	name CDATA #REQUIRED>
<!ELEMENT refresh (#PCDATA)>
<!ATTLIST refresh
	name CDATA #REQUIRED>
<!ELEMENT init (#PCDATA)>
<!ATTLIST init
	name CDATA #REQUIRED>
<!ELEMENT announce (#PCDATA)>
<!ATTLIST announce
	val CDATA #IMPLIED>
<!ELEMENT despawn (#PCDATA)>
<!ATTLIST despawn
	name CDATA #REQUIRED>
<!ELEMENT respawn (#PCDATA)>
<!ATTLIST respawn
	name CDATA #REQUIRED>
<!ELEMENT global_add_reward (#PCDATA)>
<!ATTLIST global_add_reward
	name CDATA #REQUIRED>
<!ELEMENT global_remove_reward (#PCDATA)>
<!ATTLIST global_remove_reward
	name CDATA #REQUIRED>
<!ELEMENT objects (door|spawn_ex|spawn_npc|point|boat_point|static_object|siege_toggle_npc|castle_zone|combat_flag|ctb_team|cmg_arena|territory_ward|tw_control_spot|zone|rewardlist)*>
<!ATTLIST objects
	name CDATA #REQUIRED>
<!ELEMENT door (#PCDATA)>
<!ATTLIST door
	id CDATA #REQUIRED>
<!ELEMENT siege_toggle_npc (objects)*>
<!ATTLIST siege_toggle_npc
	id CDATA #REQUIRED
	fake_id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	hp CDATA #REQUIRED>
<!ELEMENT castle_zone (#PCDATA)>
<!ATTLIST castle_zone
	name CDATA #REQUIRED
	price CDATA #REQUIRED>
<!ELEMENT tw_control_spot (#PCDATA)>
<!ATTLIST tw_control_spot
	npcs CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
	name CDATA #REQUIRED>
<!ELEMENT static_object (#PCDATA)>
<!ATTLIST static_object
	id CDATA #REQUIRED>
<!ELEMENT spawn_ex (#PCDATA)>
<!ATTLIST spawn_ex
	name CDATA #REQUIRED>
<!ELEMENT spawn_npc (#PCDATA)>
<!ATTLIST spawn_npc
	id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT combat_flag (#PCDATA)>
<!ATTLIST combat_flag
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT territory_ward (#PCDATA)>
<!ATTLIST territory_ward
	item_id CDATA #REQUIRED
	npc_id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT ctb_team (#PCDATA)>
<!ATTLIST ctb_team
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #REQUIRED
	id CDATA #REQUIRED
	mob_id CDATA #REQUIRED>
<!ELEMENT cmg_arena (#PCDATA)>
<!ELEMENT boat_point (#PCDATA)>
<!ATTLIST boat_point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	speed1 CDATA #REQUIRED
	speed2 CDATA #REQUIRED
	fuel CDATA #IMPLIED
	teleport CDATA #IMPLIED>
<!ELEMENT point (#PCDATA)>
<!ATTLIST point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #IMPLIED>
<!ELEMENT npc_say (add)*>
<!ATTLIST npc_say
	npc CDATA #REQUIRED
	chat CDATA #REQUIRED
	range CDATA #REQUIRED
	text CDATA #REQUIRED>
<!ELEMENT add (#PCDATA)*>
<!ATTLIST add
	value CDATA #REQUIRED>
<!ELEMENT teleport_players (#PCDATA)*>
<!ATTLIST teleport_players
	id CDATA #REQUIRED>
<!ELEMENT say (#PCDATA)>
<!ATTLIST say
	how CDATA #REQUIRED
	chat CDATA #REQUIRED
	range CDATA #REQUIRED
	text CDATA #REQUIRED>
<!ELEMENT play_sound (#PCDATA)>
<!ATTLIST play_sound
	type CDATA #REQUIRED
	sound CDATA #REQUIRED
	range CDATA #REQUIRED>
<!ELEMENT give_item (#PCDATA)>
<!ATTLIST give_item
	id CDATA #REQUIRED
	count CDATA #REQUIRED>
<!ELEMENT rewardlist (group|reward)*>
<!ATTLIST rewardlist
	type CDATA #REQUIRED>
<!ELEMENT group (reward)*>
<!ATTLIST group
	chance CDATA #IMPLIED>
<!ELEMENT reward (#PCDATA)>
<!ATTLIST reward
	chance CDATA #REQUIRED
	item_id CDATA #REQUIRED
	max CDATA #REQUIRED
	min CDATA #REQUIRED>

=== Kampina/wi_520/dist/game/data/events/siege/[113] cloud_mountain_fortress.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "events.dtd">
<list>
	<event id="113" name="Cloud Mountain Fortress" impl="FortressSiege">
		<parameter name="pattern" value="0 21 * * *"/>
		<on_init>
			<init name="upgradeable_doors" />
			<init name="commander_doors" />
			<init name="enter_doors" />
			<init name="siege_zones" />
			<init name="flag_zones" />
			<init name="captain_doors" />
			<init name="general_doors" />
			<spawn name="flag_pole" />
			<spawn name="peace_commanders" />
		</on_init>
		<on_start>
			<despawn name="peace_commanders" />
			<!--Спавним гвардов-->
			<spawn name="default_guards" />
			<spawn name="guards_live_with_c_center" />
			<spawn name="siege_commanders" />
			<if name="old_owner">
				<spawn name="mercenary" />
			</if>
			<else>
				<spawn name="noowner_flagdef" />
			</else>
			<if name="reinforce_1">
				<spawn name="reinforce_1" />
			</if>
			<if name="reinforce_2">
				<spawn name="reinforce_2" />
			</if>
			<if name="dwarvens">
				<spawn name="dwarvens" />
			</if>
			<!--Обновляем двери-->
			<refresh name="enter_doors" />
			<refresh name="upgradeable_doors" />
			<refresh name="commander_doors" />
			<active name="siege_zones" />
			<teleport_players id="attackers"/>
			<teleport_players id="spectators"/>
		</on_start>
		<on_stop>
			<if name="old_owner">
				<despawn name="mercenary" />
			</if>
			<else>
				<despawn name="noowner_flagdef" />
			</else>
			<despawn name="reinforce_1"/>
			<despawn name="reinforce_2"/>
			<despawn name="dwarvens"/>
			<despawn name="default_guards" />
			<despawn name="guards_live_with_c_center" />
			<despawn name="siege_commanders" />
			<!--Капитаны и менчант-->
			<spawn name="peace_commanders" />
			<!--Обновляем двери-->
			<refresh name="enter_doors" />
			<refresh name="upgradeable_doors" />
			<refresh name="commander_doors" />
			<refresh name="captain_doors" />
			<refresh name="general_doors" />
			<teleport_players id="spectators"/>
			<deactive name="siege_zones" />
		</on_stop>
		<on_time>
			<on time="-3600">
				<announce val="3600" />
			</on>
			<on time="-1800">
				<announce val="1800" />
			</on>
			<on time="-600"> <!--10 min to siege-->
				<announce val="600" />
				<stop name="registration" />
				<despawn name="merchant"/>
			</on>
			<on time="-5">
				<announce val="5" />
			</on>
			<on time="-4">
				<announce val="4" />
			</on>
			<on time="-3">
				<announce val="3" />
			</on>
			<on time="-2">
				<announce val="2" />
			</on>
			<on time="-1">
				<announce val="1" />
			</on>
			<on time="0">
				<start name="event" />
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="98">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="200">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="300">
				<give_item id="-300" count="31" />
			</on>
			<on time="310">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="403">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="512">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="596">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="600">
				<give_item id="-300" count="31" />
			</on>
			<on time="691">
				<play_sound type="SOUND" range="-1" sound="NS12_S01" />
			</on>
			<on time="785">
				<play_sound type="SOUND" range="-1" sound="NS18_F" />
			</on>
			<on time="883">
				<play_sound type="SOUND" range="-1" sound="NS02_S01" />
			</on>
			<on time="900">
				<give_item id="-300" count="31" />
			</on>
			<on time="978">
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="1076">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="1178">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="1200">
				<give_item id="-300" count="31" />
			</on>
			<on time="1288">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="1381">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="1490">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="1500">
				<give_item id="-300" count="31" />
			</on>
			<on time="1574">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="1669">
				<play_sound type="SOUND" range="-1" sound="NS12_S01" />
			</on>
			<on time="1763">
				<play_sound type="SOUND" range="-1" sound="NS18_F" />
			</on>
			<on time="1800">
				<give_item id="-300" count="31" />
			</on>
			<on time="1861">
				<play_sound type="SOUND" range="-1" sound="NS02_S01" />
			</on>
			<on time="1956">
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="2054">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="2100">
				<give_item id="-300" count="31" />
			</on>
			<on time="2156">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="2266">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="2359">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="2400">
				<give_item id="-300" count="31" />
			</on>
			<on time="2468">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="2552">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="2647">
				<play_sound type="SOUND" range="-1" sound="NS12_S01" />
			</on>
			<on time="2700">
				<give_item id="-300" count="31" />
			</on>
			<on time="2741">
				<play_sound type="SOUND" range="-1" sound="NS18_F" />
			</on>
			<on time="2839">
				<play_sound type="SOUND" range="-1" sound="NS02_S01" />
			</on>
			<on time="2934">
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="3000">
				<give_item id="-300" count="31" />
			</on>
			<on time="3032">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="3134">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="3227">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="3300">
				<give_item id="-300" count="31" />
			</on>
			<on time="3320">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="3429">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="3513">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="3600">
				<stop name="event" />
			</on>
		</on_time>
		<objects name="merchant">
			<spawn_ex name="cloud_mountain_fortress_peace_merchant" />
		</objects>
		<objects name="flag_pole">
			<static_object id="18200500" />
		</objects>
		<objects name="combat_flags">
			<combat_flag x="-53324" y="91490" z="-2690" />
			<combat_flag x="-53240" y="91497" z="-2690" />
			<combat_flag x="-53151" y="91494" z="-2690" />
		</objects>
		<objects name="peace_commanders">
			<spawn_ex name="cloud_mountain_fortress_peace_commanders" />
		</objects>
		<objects name="siege_commanders">
			<spawn_ex name="cloud_mountain_fortress_siege_commanders" />
		</objects>
		<objects name="envoy">
			<spawn_ex name="cloud_mountain_fortress_envoy" />
		</objects>
		<objects name="default_guards"> <!--дефольтные гварды спавнятся при любых условиях-->
			<spawn_ex name="cloud_mountain_fortress_default_guards" />
		</objects>
		<objects name="guards_live_with_c_center"> <!--гварды которые будут стоят пока не вворвутся в командый центр-->
			<spawn_ex name="cloud_mountain_fortress_live_with_c_center" />
		</objects>
		<objects name="noowner_flagdef"> <!--гварды охраняемые Флагполе, когда нету овнера-->
			<spawn_ex name="cloud_mountain_fortress_noowner_flagdef" />
		</objects>
		<objects name="owner_flagdef"> <!--гварды охраняемые Флагполе, когда есть овнера-->
			<spawn_ex name="cloud_mountain_fortress_owner_flagdef" />
		</objects>
		<objects name="dwarvens">
			<spawn_ex name="cloud_mountain_fortress_gunner" />
		</objects>
		<objects name="reinforce_1">
			<spawn_ex name="cloud_mountain_fortress_reinforce_1" />
		</objects>
		<objects name="reinforce_2">
			<spawn_ex name="cloud_mountain_fortress_reinforce_2" />
		</objects>
		<objects name="enter_doors">
			<door id="18200001" />
			<door id="18200010" />
		</objects>
		<objects name="upgradeable_doors">
			<door id="18200001" />
			<door id="18200010" />
		</objects>
		<objects name="commander_doors">
			<door id="18200002" />
			<door id="18200003" />
			<door id="18200011" />
			<door id="18200012" />
		</objects>
		<objects name="captain_doors">
			<door id="18200006" />
			<door id="18200007" />
		</objects>
		<objects name="general_doors">
			<door id="18200008" />
			<door id="18200009" />
		</objects>
		<objects name="mercenary_points">
			<point x="-51654" y="93918" z="-2904" />
			<point x="-51806" y="93449" z="-2832" />
			<point x="-52039" y="93351" z="-2816" />
			<point x="-52236" y="93151" z="-2816" />
			<point x="-52268" y="92908" z="-2824" />
			<point x="-52277" y="92536" z="-2824" />
			<point x="-52505" y="92338" z="-2824" />
			<point x="-52839" y="92273" z="-2824" />
			<point x="-53148" y="92216" z="-2824" />
			<point x="-53229" y="91987" z="-2824" />
		</objects>
		<objects name="mercenary">
			<spawn_ex name="cloud_mountain_fortress_mercenary" />
		</objects>
		<objects name="siege_zones">
			<zone name="[glu_ore_fort_siege]" />
		</objects>
		<objects name="flag_zones">
			<zone name="[glu_ore_fort_hq]" />
		</objects>
	</event>
</list>

=== Kampina/wi_520/dist/game/data/events/siege/[84] oren_dominion.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "events.dtd">
<list>
	<event id="84" name="Oren Dominion" impl="DominionSiege">
		<on_init>
			<init name="doors" />
			<spawn name="catapult" />
			<init name="siege_zones" />
			<init name="flag_zones" />
		</on_init>
		<on_start>
			<refresh name="doors" />
			<refresh name="mass_gatekeeper" />
			<despawn name="catapult" />
			<active name="siege_zones"/>
			<teleport_players id="owner" />
			<teleport_players id="from_residence_to_town_except_defenders" />
		</on_start>
		<on_stop>
			<refresh name="doors" />
			<refresh name="mass_gatekeeper" />
			<spawn name="catapult" />
			<teleport_players id="from_residence_to_town_except_defenders" />
			<deactive name="siege_zones" />
		</on_stop>
		<on_time>
			<on time="300">
				<give_item id="-300" count="-1" />
			</on>
			<on time="600">
				<give_item id="-300" count="-1" />
			</on>
			<on time="900">
				<give_item id="-300" count="-1" />
			</on>
			<on time="1200">
				<give_item id="-300" count="-1" />
			</on>
			<on time="1500">
				<give_item id="-300" count="-1" />
			</on>
			<on time="1800">
				<give_item id="-300" count="-1" />
			</on>
			<on time="2100">
				<give_item id="-300" count="-1" />
			</on>
			<on time="2400">
				<give_item id="-300" count="-1" />
			</on>
			<on time="2700">
				<give_item id="-300" count="-1" />
			</on>
			<on time="3000">
				<give_item id="-300" count="-1" />
			</on>
			<on time="3300">
				<give_item id="-300" count="-1" />
			</on>
			<on time="3600">
				<give_item id="-300" count="-1" />
			</on>
			<on time="3900">
				<give_item id="-300" count="-1" />
			</on>
			<on time="4200">
				<give_item id="-300" count="-1" />
			</on>
			<on time="4500">
				<give_item id="-300" count="-1" />
			</on>
			<on time="4800">
				<give_item id="-300" count="-1" />
			</on>
			<on time="5100">
				<give_item id="-300" count="-1" />
			</on>
			<on time="5400">
				<give_item id="-300" count="-1" />
			</on>
			<on time="5700">
				<give_item id="-300" count="-1" />
			</on>
			<on time="6000">
				<give_item id="-300" count="-1" />
			</on>
			<on time="6300">
				<give_item id="-300" count="-1" />
			</on>
			<on time="6600">
				<give_item id="-300" count="-1" />
			</on>
			<on time="6900">
				<give_item id="-300" count="-1" />
			</on>
		</on_time>
		<objects name="doors">
			<door id="22190001" />
			<door id="22190002" />
			<door id="22190003" />
			<door id="22190004" />
			<door id="22190005" />
			<door id="22190006" />
			<door id="22190007" />
			<door id="22190008" />
			<door id="22190009" />
		</objects>
		<objects name="siege_zones">
			<zone name="[oren_castle_siege]" />
		</objects>
		<objects name="flag_zones">
			<zone name="[gludio_castle_hq]" />
			<zone name="[dion_castle_hq]" />
			<zone name="[giran_castle_hq]" />
			<zone name="[oren_castle_hq]" />
			<zone name="[aden_castle_hq]" />
			<zone name="[innadrile_castle_hq]" />
			<zone name="[godad_castle_hq]" />
			<zone name="[rune_castle_hq]" />
			<zone name="[schuttgart_castle_hq]" />
		</objects>
		<objects name="territory_npc">
			<spawn_ex name="territory_manager_4" />
		</objects>
		<objects name="catapult">
			<spawn_ex name="Oren_castle_mercenary" />
		</objects>
		<objects name="ward_81">
			<territory_ward item_id="13560" npc_id="36572" x="82750" y="36840" z="-2293" /> <!--Gludio Ward-->
		</objects>
		<objects name="ward_82">
			<territory_ward item_id="13561" npc_id="36573" x="82750" y="36920" z="-2293" /> <!--Dion Ward-->
		</objects>
		<objects name="ward_83">
			<territory_ward item_id="13562" npc_id="36574" x="82750" y="37000" z="-2293" /> <!--Giran Ward-->
		</objects>
		<objects name="ward_84">
			<territory_ward item_id="13563" npc_id="36575" x="82750" y="37080" z="-2293" /> <!--Oren Ward-->
		</objects>
		<objects name="ward_85">
			<territory_ward item_id="13564" npc_id="36576" x="82750" y="37160" z="-2293" /> <!--Aden Ward-->
		</objects>
		<objects name="ward_86">
			<territory_ward item_id="13565" npc_id="36577" x="82750" y="37240" z="-2293" /> <!--Innadril Ward-->
		</objects>
		<objects name="ward_87">
			<territory_ward item_id="13566" npc_id="36578" x="82750" y="37320" z="-2293" /> <!--Goddard Ward-->
		</objects>
		<objects name="ward_88">
			<territory_ward item_id="13567" npc_id="36579" x="82750" y="37400" z="-2293" /> <!--Rune Ward-->
		</objects>
		<objects name="ward_89">
			<territory_ward item_id="13568" npc_id="36580" x="82750" y="37480" z="-2293" /> <!--Schuttgart Ward-->
		</objects>
	</event>
</list>

=== Kampina/wi_520/dist/game/data/events/siege/[110] swamp_fortress.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "events.dtd">
<list>
	<event id="110" name="Swamp Fortress" impl="FortressSiege">
		<parameter name="pattern" value="0 21 * * *"/>
		<on_init>
			<init name="upgradeable_doors" />
			<init name="commander_doors" />
			<init name="enter_doors" />
			<init name="siege_zones" />
			<init name="flag_zones" />
			<init name="captain_doors" />
			<init name="general_doors" />
			<spawn name="flag_pole" />
			<spawn name="peace_commanders" />
		</on_init>
		<on_start>
			<despawn name="peace_commanders" />
			<!--Спавним гвардов-->
			<spawn name="default_guards" />
			<spawn name="guards_live_with_c_center" />
			<spawn name="siege_commanders" />
			<if name="old_owner">
				<spawn name="mercenary" />
			</if>
			<else>
				<spawn name="noowner_flagdef" />
			</else>
			<if name="reinforce_1">
				<spawn name="reinforce_1" />
			</if>
			<if name="reinforce_2">
				<spawn name="reinforce_2" />
			</if>
			<if name="dwarvens">
				<spawn name="dwarvens" />
			</if>
			<!--Обновляем двери-->
			<refresh name="enter_doors" />
			<refresh name="upgradeable_doors" />
			<refresh name="commander_doors" />
			<active name="siege_zones" />
			<teleport_players id="attackers"/>
			<teleport_players id="spectators"/>
		</on_start>
		<on_stop>
			<if name="old_owner">
				<despawn name="mercenary" />
			</if>
			<else>
				<despawn name="noowner_flagdef" />
			</else>
			<despawn name="reinforce_1"/>
			<despawn name="reinforce_2"/>
			<despawn name="dwarvens"/>
			<despawn name="default_guards" />
			<despawn name="guards_live_with_c_center" />
			<despawn name="siege_commanders" />
			<!--Капитаны и менчант-->
			<spawn name="peace_commanders" />
			<!--Обновляем двери-->
			<refresh name="enter_doors" />
			<refresh name="upgradeable_doors" />
			<refresh name="commander_doors" />
			<refresh name="captain_doors" />
			<refresh name="general_doors" />
			<teleport_players id="spectators"/>
			<deactive name="siege_zones" />
		</on_stop>
		<on_time>
			<on time="-3600">
				<announce val="3600" />
			</on>
			<on time="-1800">
				<announce val="1800" />
			</on>
			<on time="-600"> <!--10 min to siege-->
				<announce val="600" />
				<stop name="registration" />
				<despawn name="merchant"/>
			</on>
			<on time="-5">
				<announce val="5" />
			</on>
			<on time="-4">
				<announce val="4" />
			</on>
			<on time="-3">
				<announce val="3" />
			</on>
			<on time="-2">
				<announce val="2" />
			</on>
			<on time="-1">
				<announce val="1" />
			</on>
			<on time="0">
				<start name="event" />
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="98">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="200">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="300">
				<give_item id="-300" count="31" />
			</on>
			<on time="310">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="403">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="512">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="596">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="600">
				<give_item id="-300" count="31" />
			</on>
			<on time="691">
				<play_sound type="SOUND" range="-1" sound="NS12_S01" />
			</on>
			<on time="785">
				<play_sound type="SOUND" range="-1" sound="NS18_F" />
			</on>
			<on time="883">
				<play_sound type="SOUND" range="-1" sound="NS02_S01" />
			</on>
			<on time="900">
				<give_item id="-300" count="31" />
			</on>
			<on time="978">
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="1076">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="1178">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="1200">
				<give_item id="-300" count="31" />
			</on>
			<on time="1288">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="1381">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="1490">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="1500">
				<give_item id="-300" count="31" />
			</on>
			<on time="1574">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="1669">
				<play_sound type="SOUND" range="-1" sound="NS12_S01" />
			</on>
			<on time="1763">
				<play_sound type="SOUND" range="-1" sound="NS18_F" />
			</on>
			<on time="1800">
				<give_item id="-300" count="31" />
			</on>
			<on time="1861">
				<play_sound type="SOUND" range="-1" sound="NS02_S01" />
			</on>
			<on time="1956">
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="2054">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="2100">
				<give_item id="-300" count="31" />
			</on>
			<on time="2156">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="2266">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="2359">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="2400">
				<give_item id="-300" count="31" />
			</on>
			<on time="2468">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="2552">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="2647">
				<play_sound type="SOUND" range="-1" sound="NS12_S01" />
			</on>
			<on time="2700">
				<give_item id="-300" count="31" />
			</on>
			<on time="2741">
				<play_sound type="SOUND" range="-1" sound="NS18_F" />
			</on>
			<on time="2839">
				<play_sound type="SOUND" range="-1" sound="NS02_S01" />
			</on>
			<on time="2934">
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="3000">
				<give_item id="-300" count="31" />
			</on>
			<on time="3032">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="3134">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="3227">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="3300">
				<give_item id="-300" count="31" />
			</on>
			<on time="3320">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="3429">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="3513">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="3600">
				<stop name="event" />
			</on>
		</on_time>
		<objects name="merchant">
			<spawn_ex name="swamp_fortress_peace_merchant" />
		</objects>
		<objects name="flag_pole">
			<static_object id="22160500" />
		</objects>
		<objects name="combat_flags">
			<combat_flag x="69861" y="-61150" z="-2655" />
			<combat_flag x="69943" y="-61177" z="-2655" />
			<combat_flag x="70014" y="-61208" z="-2655" />
		</objects>
		<objects name="peace_commanders">
			<spawn_ex name="swamp_fortress_peace_commanders" />
		</objects>
		<objects name="siege_commanders">
			<spawn_ex name="swamp_fortress_siege_commanders" />
		</objects>
		<objects name="envoy">
			<spawn_ex name="swamp_fortress_envoy" />
		</objects>
		<objects name="default_guards"> <!--дефольтные гварды спавнятся при любых условиях-->
			<spawn_ex name="swamp_fortress_default_guards" />
		</objects>
		<objects name="guards_live_with_c_center"> <!--гварды которые будут стоят пока не вворвутся в командый центр-->
			<spawn_ex name="swamp_fortress_live_with_c_center" />
		</objects>
		<objects name="noowner_flagdef"> <!--гварды охраняемые Флагполе, когда нету овнера-->
			<spawn_ex name="swamp_fortress_noowner_flagdef" />
		</objects>
		<objects name="owner_flagdef"> <!--гварды охраняемые Флагполе, когда есть овнера-->
			<spawn_ex name="swamp_fortress_owner_flagdef" />
		</objects>
		<objects name="dwarvens">
			<spawn_ex name="swamp_fortress_gunner" />
		</objects>
		<objects name="reinforce_1">
			<spawn_ex name="swamp_fortress_reinforce_1" />
		</objects>
		<objects name="reinforce_2">
			<spawn_ex name="swamp_fortress_reinforce_2" />
		</objects>
		<objects name="enter_doors">
			<door id="22160001" />
			<door id="22160012" />
		</objects>
		<objects name="upgradeable_doors">
			<door id="22160001" />
			<door id="22160012" />
		</objects>
		<objects name="commander_doors">
			<door id="22160008" />
			<door id="22160009" />
			<door id="22160005" />
			<door id="22160004" />
		</objects>
		<objects name="captain_doors">
			<door id="22160010" />
			<door id="22160011" />
		</objects>
		<objects name="general_doors">
			<door id="22160006" />
			<door id="22160007" />
		</objects>
		<objects name="mercenary_points">
			<point x="68469" y="-64996" z="-2736" />
			<point x="68524" y="-64684" z="-2736" />
			<point x="68576" y="-64365" z="-2760" />
			<point x="68642" y="-64103" z="-2776" />
			<point x="68722" y="-63886" z="-2784" />
			<point x="68829" y="-63646" z="-2784" />
			<point x="68976" y="-63316" z="-2784" />
			<point x="69153" y="-62979" z="-2784" />
			<point x="69269" y="-62724" z="-2784" />
			<point x="69522" y="-62173" z="-2784" />
		</objects>
		<objects name="mercenary">
			<spawn_ex name="swamp_fortress_mercenary" />
		</objects>
		<objects name="siege_zones">
			<zone name="[rune_fort_siege]" />
		</objects>
		<objects name="flag_zones">
			<zone name="[rune_fort_hq]" />
		</objects>
	</event>
</list>
