=== Kampina/wi_520/dist/game/data/events/events.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (event)*>
<!ELEMENT event (parameter|on_start|on_stop|on_init|on_time|objects)*>
<!ATTLIST event
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	impl CDATA #REQUIRED>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT on_start  (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward)*>
<!ELEMENT on_stop   (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward)*>
<!ELEMENT on_init   (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward)*>
<!ELEMENT on        (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward)*>
<!ELEMENT if        (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward)*>
<!ELEMENT ifnot     (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward)*>
<!ELEMENT else      (if|ifnot|else|start|stop|spawn|despawn|respawn|npc_say|say|play_sound|open|close|refresh|init|announce|active|deactive|give_item|teleport_players|global_add_reward|global_remove_reward)*>
<!ATTLIST if
	name CDATA #REQUIRED>
<!ATTLIST ifnot
	name CDATA #REQUIRED>
<!ELEMENT on_time (on)*>
<!ATTLIST on
	time CDATA #REQUIRED>
<!ELEMENT start (#PCDATA)>
<!ATTLIST start
	name CDATA #REQUIRED>
<!ELEMENT stop (#PCDATA)>
<!ATTLIST stop
	name CDATA #REQUIRED>
<!ELEMENT spawn (#PCDATA)>
<!ATTLIST spawn
	name CDATA #REQUIRED>
<!ELEMENT open (#PCDATA)>
<!ATTLIST open
	name CDATA #REQUIRED>
<!ELEMENT close (#PCDATA)>
<!ATTLIST close
	name CDATA #REQUIRED>
<!ELEMENT active (#PCDATA)>
<!ATTLIST active
	name CDATA #REQUIRED>
<!ELEMENT deactive (#PCDATA)>
<!ATTLIST deactive
	name CDATA #REQUIRED>
<!ELEMENT refresh (#PCDATA)>
<!ATTLIST refresh
	name CDATA #REQUIRED>
<!ELEMENT init (#PCDATA)>
<!ATTLIST init
	name CDATA #REQUIRED>
<!ELEMENT announce (#PCDATA)>
<!ATTLIST announce
	val CDATA #IMPLIED>
<!ELEMENT despawn (#PCDATA)>
<!ATTLIST despawn
	name CDATA #REQUIRED>
<!ELEMENT respawn (#PCDATA)>
<!ATTLIST respawn
	name CDATA #REQUIRED>
<!ELEMENT global_add_reward (#PCDATA)>
<!ATTLIST global_add_reward
	name CDATA #REQUIRED>
<!ELEMENT global_remove_reward (#PCDATA)>
<!ATTLIST global_remove_reward
	name CDATA #REQUIRED>
<!ELEMENT objects (door|spawn_ex|spawn_npc|point|boat_point|static_object|siege_toggle_npc|castle_zone|combat_flag|ctb_team|cmg_arena|territory_ward|tw_control_spot|zone|rewardlist)*>
<!ATTLIST objects
	name CDATA #REQUIRED>
<!ELEMENT door (#PCDATA)>
<!ATTLIST door
	id CDATA #REQUIRED>
<!ELEMENT siege_toggle_npc (objects)*>
<!ATTLIST siege_toggle_npc
	id CDATA #REQUIRED
	fake_id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	hp CDATA #REQUIRED>
<!ELEMENT castle_zone (#PCDATA)>
<!ATTLIST castle_zone
	name CDATA #REQUIRED
	price CDATA #REQUIRED>
<!ELEMENT tw_control_spot (#PCDATA)>
<!ATTLIST tw_control_spot
	npcs CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
	name CDATA #REQUIRED>
<!ELEMENT static_object (#PCDATA)>
<!ATTLIST static_object
	id CDATA #REQUIRED>
<!ELEMENT spawn_ex (#PCDATA)>
<!ATTLIST spawn_ex
	name CDATA #REQUIRED>
<!ELEMENT spawn_npc (#PCDATA)>
<!ATTLIST spawn_npc
	id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT combat_flag (#PCDATA)>
<!ATTLIST combat_flag
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT territory_ward (#PCDATA)>
<!ATTLIST territory_ward
	item_id CDATA #REQUIRED
	npc_id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT ctb_team (#PCDATA)>
<!ATTLIST ctb_team
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #REQUIRED
	id CDATA #REQUIRED
	mob_id CDATA #REQUIRED>
<!ELEMENT cmg_arena (#PCDATA)>
<!ELEMENT boat_point (#PCDATA)>
<!ATTLIST boat_point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	speed1 CDATA #REQUIRED
	speed2 CDATA #REQUIRED
	fuel CDATA #IMPLIED
	teleport CDATA #IMPLIED>
<!ELEMENT point (#PCDATA)>
<!ATTLIST point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #IMPLIED>
<!ELEMENT npc_say (add)*>
<!ATTLIST npc_say
	npc CDATA #REQUIRED
	chat CDATA #REQUIRED
	range CDATA #REQUIRED
	text CDATA #REQUIRED>
<!ELEMENT add (#PCDATA)*>
<!ATTLIST add
	value CDATA #REQUIRED>
<!ELEMENT teleport_players (#PCDATA)*>
<!ATTLIST teleport_players
	id CDATA #REQUIRED>
<!ELEMENT say (#PCDATA)>
<!ATTLIST say
	how CDATA #REQUIRED
	chat CDATA #REQUIRED
	range CDATA #REQUIRED
	text CDATA #REQUIRED>
<!ELEMENT play_sound (#PCDATA)>
<!ATTLIST play_sound
	type CDATA #REQUIRED
	sound CDATA #REQUIRED
	range CDATA #REQUIRED>
<!ELEMENT give_item (#PCDATA)>
<!ATTLIST give_item
	id CDATA #REQUIRED
	count CDATA #REQUIRED>
<!ELEMENT rewardlist (group|reward)*>
<!ATTLIST rewardlist
	type CDATA #REQUIRED>
<!ELEMENT group (reward)*>
<!ATTLIST group
	chance CDATA #IMPLIED>
<!ELEMENT reward (#PCDATA)>
<!ATTLIST reward
	chance CDATA #REQUIRED
	item_id CDATA #REQUIRED
	max CDATA #REQUIRED
	min CDATA #REQUIRED>

=== Kampina/wi_520/dist/game/data/events/siege/[114] tanor_fortress.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "events.dtd">
<list>
	<event id="114" name="Tanor Fortress" impl="FortressSiege">
		<parameter name="pattern" value="0 9 * * *"/>
		<on_init>
			<init name="upgradeable_doors" />
			<init name="commander_doors" />
			<init name="enter_doors" />
			<init name="siege_zones" />
			<init name="flag_zones" />
			<init name="captain_doors" />
			<spawn name="flag_pole" />
			<spawn name="peace_commanders" />
		</on_init>
		<on_start>
			<despawn name="peace_commanders" />
			<!--Спавним гвардов-->
			<spawn name="default_guards" />
			<spawn name="guards_live_with_c_center" />
			<spawn name="siege_commanders" />
			<if name="old_owner">
				<spawn name="mercenary" />
			</if>
			<else>
				<spawn name="noowner_flagdef" />
			</else>
			<if name="reinforce_1">
				<spawn name="reinforce_1" />
			</if>
			<if name="reinforce_2">
				<spawn name="reinforce_2" />
			</if>
			<if name="dwarvens">
				<spawn name="dwarvens" />
			</if>
			<!--Обновляем двери-->
			<refresh name="enter_doors" />
			<refresh name="upgradeable_doors" />
			<refresh name="commander_doors" />
			<active name="siege_zones" />
			<teleport_players id="attackers"/>
			<teleport_players id="spectators"/>
		</on_start>
		<on_stop>
			<if name="old_owner">
				<despawn name="mercenary" />
			</if>
			<else>
				<despawn name="noowner_flagdef" />
			</else>
			<despawn name="reinforce_1"/>
			<despawn name="reinforce_2"/>
			<despawn name="dwarvens"/>
			<despawn name="default_guards" />
			<despawn name="guards_live_with_c_center" />
			<despawn name="siege_commanders" />
			<!--Капитаны и менчант-->
			<spawn name="peace_commanders" />
			<!--Обновляем двери-->
			<refresh name="enter_doors" />
			<refresh name="upgradeable_doors" />
			<refresh name="commander_doors" />
			<refresh name="captain_doors" />
			<teleport_players id="spectators"/>
			<deactive name="siege_zones" />
		</on_stop>
		<on_time>
			<on time="-3600">
				<announce val="3600" />
			</on>
			<on time="-1800">
				<announce val="1800" />
			</on>
			<on time="-600"> <!--10 min to siege-->
				<announce val="600" />
				<stop name="registration" />
				<despawn name="merchant"/>
			</on>
			<on time="-5">
				<announce val="5" />
			</on>
			<on time="-4">
				<announce val="4" />
			</on>
			<on time="-3">
				<announce val="3" />
			</on>
			<on time="-2">
				<announce val="2" />
			</on>
			<on time="-1">
				<announce val="1" />
			</on>
			<on time="0">
				<start name="event" />
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="98">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="200">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="300">
				<give_item id="-300" count="31" />
			</on>
			<on time="310">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="403">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="512">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="596">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="600">
				<give_item id="-300" count="31" />
			</on>
			<on time="691">
				<play_sound type="SOUND" range="-1" sound="NS12_S01" />
			</on>
			<on time="785">
				<play_sound type="SOUND" range="-1" sound="NS18_F" />
			</on>
			<on time="883">
				<play_sound type="SOUND" range="-1" sound="NS02_S01" />
			</on>
			<on time="900">
				<give_item id="-300" count="31" />
			</on>
			<on time="978">
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="1076">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="1178">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="1200">
				<give_item id="-300" count="31" />
			</on>
			<on time="1288">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="1381">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="1490">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="1500">
				<give_item id="-300" count="31" />
			</on>
			<on time="1574">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="1669">
				<play_sound type="SOUND" range="-1" sound="NS12_S01" />
			</on>
			<on time="1763">
				<play_sound type="SOUND" range="-1" sound="NS18_F" />
			</on>
			<on time="1800">
				<give_item id="-300" count="31" />
			</on>
			<on time="1861">
				<play_sound type="SOUND" range="-1" sound="NS02_S01" />
			</on>
			<on time="1956">
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="2054">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="2100">
				<give_item id="-300" count="31" />
			</on>
			<on time="2156">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="2266">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="2359">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="2400">
				<give_item id="-300" count="31" />
			</on>
			<on time="2468">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="2552">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="2647">
				<play_sound type="SOUND" range="-1" sound="NS12_S01" />
			</on>
			<on time="2700">
				<give_item id="-300" count="31" />
			</on>
			<on time="2741">
				<play_sound type="SOUND" range="-1" sound="NS18_F" />
			</on>
			<on time="2839">
				<play_sound type="SOUND" range="-1" sound="NS02_S01" />
			</on>
			<on time="2934">
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="3000">
				<give_item id="-300" count="31" />
			</on>
			<on time="3032">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="3134">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="3227">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="3300">
				<give_item id="-300" count="31" />
			</on>
			<on time="3320">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="3429">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="3513">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="3600">
				<stop name="event" />
			</on>
		</on_time>
		<objects name="merchant">
			<spawn_ex name="tanor_fortress_peace_merchant" />
		</objects>
		<objects name="flag_pole">
			<static_object id="21220500" />
		</objects>
		<objects name="combat_flags">
			<combat_flag x="60256" y="139716" z="-1623" />
			<combat_flag x="60341" y="139701" z="-1623" />
			<combat_flag x="60418" y="139681" z="-1623" />
		</objects>
		<objects name="peace_commanders">
			<spawn_ex name="tanor_fortress_peace_commanders" />
		</objects>
		<objects name="siege_commanders">
			<spawn_ex name="tanor_fortress_siege_commanders" />
		</objects>
		<objects name="envoy">
			<spawn_ex name="tanor_fortress_envoy" />
		</objects>
		<objects name="default_guards"> <!--дефольтные гварды спавнятся при любых условиях-->
			<spawn_ex name="tanor_fortress_default_guards" />
		</objects>
		<objects name="guards_live_with_c_center"> <!--гварды которые будут стоят пока не вворвутся в командый центр-->
			<spawn_ex name="tanor_fortress_live_with_c_center" />
		</objects>
		<objects name="noowner_flagdef"> <!--гварды охраняемые Флагполе, когда нету овнера-->
			<spawn_ex name="tanor_fortress_noowner_flagdef" />
		</objects>
		<objects name="owner_flagdef"> <!--гварды охраняемые Флагполе, когда есть овнера-->
			<spawn_ex name="tanor_fortress_owner_flagdef" />
		</objects>
		<objects name="dwarvens">
			<spawn_ex name="tanor_fortress_gunner" />
		</objects>
		<objects name="reinforce_1">
			<spawn_ex name="tanor_fortress_reinforce_1" />
		</objects>
		<objects name="reinforce_2">
			<spawn_ex name="tanor_fortress_reinforce_2" />
		</objects>
		<objects name="enter_doors">
			<door id="21220001" />
			<door id="21220008" />
		</objects>
		<objects name="upgradeable_doors">
			<door id="21220001" />
			<door id="21220008" />
		</objects>
		<objects name="commander_doors">
			<door id="21220002" />
			<door id="21220003" />
			<door id="21220006" />
			<door id="21220007" />
		</objects>
		<objects name="captain_doors">
			<door id="21220004" />
			<door id="21220005" />
		</objects>
		<objects name="mercenary_points">
			<point x="61572" y="141942" z="-1784" />
			<point x="61545" y="141725" z="-1768" />
			<point x="61555" y="141487" z="-1760" />
			<point x="61626" y="141270" z="-1752" />
			<point x="61635" y="141071" z="-1752" />
			<point x="61552" y="140809" z="-1752" />
			<point x="61506" y="140486" z="-1752" />
			<point x="61192" y="140223" z="-1752" />
			<point x="60700" y="140250" z="-1752" />
			<point x="60499" y="140159" z="-1752" />
		</objects>
		<objects name="mercenary">
			<spawn_ex name="tanor_fortress_mercenary" />
		</objects>
		<objects name="siege_zones">
			<zone name="[di_gi_fort_siege]" />
		</objects>
		<objects name="flag_zones">
			<zone name="[di_gi_fort_hq]" />
		</objects>
	</event>
</list>

=== Kampina/wi_520/dist/game/data/events/siege/[103] hive_fortress.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "events.dtd">
<list>
	<event id="103" name="Hive Fortress" impl="FortressSiege">
		<parameter name="pattern" value="0 9 * * *"/>
		<on_init>
			<init name="upgradeable_doors" />
			<init name="commander_doors" />
			<init name="enter_doors" />
			<init name="siege_zones" />
			<init name="flag_zones" />
			<init name="captain_doors" />
			<spawn name="flag_pole" />
			<spawn name="peace_commanders" />
		</on_init>
		<on_start>
			<despawn name="peace_commanders" />
			<!--Спавним гвардов-->
			<spawn name="default_guards" />
			<spawn name="guards_live_with_c_center" />
			<spawn name="siege_commanders" />
			<if name="old_owner">
				<spawn name="mercenary" />
			</if>
			<else>
				<spawn name="noowner_flagdef" />
			</else>
			<if name="reinforce_1">
				<spawn name="reinforce_1" />
			</if>
			<if name="reinforce_2">
				<spawn name="reinforce_2" />
			</if>
			<if name="dwarvens">
				<spawn name="dwarvens" />
			</if>
			<!--Обновляем двери-->
			<refresh name="enter_doors" />
			<refresh name="upgradeable_doors" />
			<refresh name="commander_doors" />
			<active name="siege_zones" />
			<teleport_players id="attackers"/>
			<teleport_players id="spectators"/>
		</on_start>
		<on_stop>
			<if name="old_owner">
				<despawn name="mercenary" />
			</if>
			<else>
				<despawn name="noowner_flagdef" />
			</else>
			<despawn name="reinforce_1"/>
			<despawn name="reinforce_2"/>
			<despawn name="dwarvens"/>
			<despawn name="default_guards" />
			<despawn name="guards_live_with_c_center" />
			<despawn name="siege_commanders" />
			<!--Капитаны и менчант-->
			<spawn name="peace_commanders" />
			<!--Обновляем двери-->
			<refresh name="enter_doors" />
			<refresh name="upgradeable_doors" />
			<refresh name="commander_doors" />
			<refresh name="captain_doors" />
			<teleport_players id="spectators"/>
			<deactive name="siege_zones" />
		</on_stop>
		<on_time>
			<on time="-3600">
				<announce val="3600" />
			</on>
			<on time="-1800">
				<announce val="1800" />
			</on>
			<on time="-600"> <!--10 min to siege-->
				<announce val="600" />
				<stop name="registration" />
				<despawn name="merchant"/>
			</on>
			<on time="-5">
				<announce val="5" />
			</on>
			<on time="-4">
				<announce val="4" />
			</on>
			<on time="-3">
				<announce val="3" />
			</on>
			<on time="-2">
				<announce val="2" />
			</on>
			<on time="-1">
				<announce val="1" />
			</on>
			<on time="0">
				<start name="event" />
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="98">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="200">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="300">
				<give_item id="-300" count="31" />
			</on>
			<on time="310">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="403">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="512">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="596">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="600">
				<give_item id="-300" count="31" />
			</on>
			<on time="691">
				<play_sound type="SOUND" range="-1" sound="NS12_S01" />
			</on>
			<on time="785">
				<play_sound type="SOUND" range="-1" sound="NS18_F" />
			</on>
			<on time="883">
				<play_sound type="SOUND" range="-1" sound="NS02_S01" />
			</on>
			<on time="900">
				<give_item id="-300" count="31" />
			</on>
			<on time="978">
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="1076">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="1178">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="1200">
				<give_item id="-300" count="31" />
			</on>
			<on time="1288">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="1381">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="1490">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="1500">
				<give_item id="-300" count="31" />
			</on>
			<on time="1574">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="1669">
				<play_sound type="SOUND" range="-1" sound="NS12_S01" />
			</on>
			<on time="1763">
				<play_sound type="SOUND" range="-1" sound="NS18_F" />
			</on>
			<on time="1800">
				<give_item id="-300" count="31" />
			</on>
			<on time="1861">
				<play_sound type="SOUND" range="-1" sound="NS02_S01" />
			</on>
			<on time="1956">
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="2054">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="2100">
				<give_item id="-300" count="31" />
			</on>
			<on time="2156">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="2266">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="2359">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="2400">
				<give_item id="-300" count="31" />
			</on>
			<on time="2468">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="2552">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="2647">
				<play_sound type="SOUND" range="-1" sound="NS12_S01" />
			</on>
			<on time="2700">
				<give_item id="-300" count="31" />
			</on>
			<on time="2741">
				<play_sound type="SOUND" range="-1" sound="NS18_F" />
			</on>
			<on time="2839">
				<play_sound type="SOUND" range="-1" sound="NS02_S01" />
			</on>
			<on time="2934">
				<play_sound type="SOUND" range="-1" sound="NS20_F" />
			</on>
			<on time="3000">
				<give_item id="-300" count="31" />
			</on>
			<on time="3032">
				<play_sound type="SOUND" range="-1" sound="NB02_F" />
			</on>
			<on time="3134">
				<play_sound type="SOUND" range="-1" sound="NS19_S01" />
			</on>
			<on time="3227">
				<play_sound type="SOUND" range="-1" sound="NS12_F" />
			</on>
			<on time="3300">
				<give_item id="-300" count="31" />
			</on>
			<on time="3320">
				<play_sound type="SOUND" range="-1" sound="NS19_F" />
			</on>
			<on time="3429">
				<play_sound type="SOUND" range="-1" sound="NS18_S01" />
			</on>
			<on time="3513">
				<play_sound type="SOUND" range="-1" sound="NS02_F" />
			</on>
			<on time="3600">
				<stop name="event" />
			</on>
		</on_time>
		<objects name="merchant">
			<spawn_ex name="hive_fortress_peace_merchant" />
		</objects>
		<objects name="flag_pole">
			<static_object id="20230500" />
		</objects>
		<objects name="combat_flags">
			<combat_flag x="16664" y="188321" z="-2793" />
			<combat_flag x="16723" y="188287" z="-2793" />
			<combat_flag x="16787" y="188241" z="-2793" />
		</objects>
		<objects name="peace_commanders">
			<spawn_ex name="hive_fortress_peace_commanders" />
		</objects>
		<objects name="siege_commanders">
			<spawn_ex name="hive_fortress_siege_commanders" />
		</objects>
		<objects name="envoy">
			<spawn_ex name="hive_fortress_envoy" />
		</objects>
		<objects name="default_guards"> <!--дефольтные гварды спавнятся при любых условиях-->
			<spawn_ex name="hive_fortress_default_guards" />
		</objects>
		<objects name="guards_live_with_c_center"> <!--гварды которые будут стоят пока не вворвутся в командый центр-->
			<spawn_ex name="hive_fortress_live_with_c_center" />
		</objects>
		<objects name="noowner_flagdef"> <!--гварды охраняемые Флагполе, когда нету овнера-->
			<spawn_ex name="hive_fortress_noowner_flagdef" />
		</objects>
		<objects name="owner_flagdef"> <!--гварды охраняемые Флагполе, когда есть овнера-->
			<spawn_ex name="hive_fortress_owner_flagdef" />
		</objects>
		<objects name="dwarvens">
			<spawn_ex name="hive_fortress_gunner" />
		</objects>
		<objects name="reinforce_1">
			<spawn_ex name="hive_fortress_reinforce_1" />
		</objects>
		<objects name="reinforce_2">
			<spawn_ex name="hive_fortress_reinforce_2" />
		</objects>
		<objects name="enter_doors">
			<door id="20230003" />
			<door id="20230010" />
		</objects>
		<objects name="upgradeable_doors">
			<door id="20230003" />
			<door id="20230006" />
			<door id="20230007" />
			<door id="20230010" />
		</objects>
		<objects name="commander_doors">
			<door id="20230004" />
			<door id="20230005" />
		</objects>
		<objects name="captain_doors">
			<door id="20230008" />
			<door id="20230009" />
		</objects>
		<objects name="mercenary_points">
			<point x="18869" y="189912" z="-2992" />
			<point x="18623" y="190046" z="-2952" />
			<point x="18365" y="190098" z="-2928" />
			<point x="18109" y="190077" z="-2920" />
			<point x="17927" y="189921" z="-2920" />
			<point x="17763" y="189682" z="-2920" />
			<point x="17619" y="189493" z="-2920" />
			<point x="17462" y="189294" z="-2920" />
			<point x="17207" y="188960" z="-2920" />
			<point x="17029" y="188723" z="-2920" />
		</objects>
		<objects name="mercenary">
			<spawn_ex name="hive_fortress_mercenary" />
		</objects>
		<objects name="siege_zones">
			<zone name="[dion_fort_siege]" />
		</objects>
		<objects name="flag_zones">
			<zone name="[dion_fort_hq]" />
		</objects>
	</event>
</list>
