=== Kampina/wi_520/dist/game/data/xsd/fortData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fort">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded" minOccurs="0">
							<xs:element name="spawns">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="npc" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute type="xs:int" name="id" use="optional" />
												<xs:attribute type="xs:int" name="x" use="required" />
												<xs:attribute type="xs:int" name="y" use="required" />
												<xs:attribute type="xs:int" name="z" use="required" />
												<xs:attribute type="xs:int" name="heading" use="optional" />
												<xs:attribute type="xs:int" name="castleId" use="optional" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="skills">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="skill" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute type="xs:int" name="id" use="required" />
												<xs:attribute type="xs:int" name="lvl" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="doors">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="door" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute type="xs:int" name="id" use="required" /><xs:attribute type="xs:string" name="group" use="optional" /></xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:choice>
						<xs:attribute type="xs:short" name="id" />
						<xs:attribute type="xs:string" name="name" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Kampina/wi_520/dist/game/data/residences/fortresses/White_sands.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/fortData.xsd">
	<fort id="108" name="White Sands Fortress">
	<doors>
		<door id="23240001" />
		<door id="23240008" />
		<door id="23240002" group="commander_doors" />
		<door id="23240003" group="commander_doors" />
		<door id="23240006" group="commander_doors" />
		<door id="23240007" group="commander_doors" />
		<door id="23240004" group="captain_doors" />
		<door id="23240005" group="captain_doors" />
	</doors>
		<skills>
			<skill id="590" lvl="1" />
			<skill id="592" lvl="1" />
			<skill id="593" lvl="1" />
			<skill id="595" lvl="1" />
		</skills>
	</fort>
</list>

=== Kampina/wi_520/dist/game/data/residences/fortresses/Cloud_mountain.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/fortData.xsd">
	<fort id="113" name="Cloud Mountain Fortress">
	<doors>
		<door id="18200001" />
		<door id="18200010" />
		<door id="18200002" group="commander_doors" />
		<door id="18200003" group="commander_doors" />
		<door id="18200011" group="commander_doors" />
		<door id="18200012" group="commander_doors" />
		<door id="18200006" group="captain_doors" />
		<door id="18200007" group="captain_doors" />
		<door id="18200008" group="general_doors" />
		<door id="18200009" group="general_doors" />
	</doors>
		<skills>
			<skill id="590" lvl="1" />
			<skill id="592" lvl="1" />
			<skill id="593" lvl="1" />
			<skill id="595" lvl="1" />
		</skills>
	</fort>
</list>
