=== Kampina/wi_520/dist/game/data/xsd/fractions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="fraction" minOccurs="1" maxOccurs="64">
					<xs:complexType>
						<xs:attribute name="race" type="xs:token" use="required" />
						<xs:attribute name="side" type="xs:token" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Kampina/wi_520/dist/game/data/character/fractions.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/fractions.xsd">
	<fraction race="HUMAN" side="LIGHT" />
	<fraction race="ELF" side="LIGHT" />
	<fraction race="HIGH_ELF" side="LIGHT" />
	<fraction race="DARK_ELF" side="DARK" />
	<fraction race="KAMAEL" side="DARK" />
	<fraction race="ERTHEIA" side="DARK" />
	<fraction race="ORC" side="NONE" />
	<fraction race="DWARF" side="NONE" />
</list>
